# Generated by Django 4.2.27 on 2026-01-26 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("DOCTOR", "Doctor"), ("PATIENT", "Patient")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "google_refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted Google OAuth refresh token for calendar access",
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Doctor's specialization (only for doctors)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profile",
            },
        ),
    ]
