# Generated by Django 4.2.27 on 2026-01-27 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ical_token",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                help_text="Unique token for iCal feed subscription",
                null=True,
            ),
        ),
    ]
