# Generated by Django 4.2.27 on 2026-01-27 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_ical_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="ical_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique token for iCal feed subscription",
                unique=True,
            ),
        ),
    ]
