# Generated by Django
from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for row in UserProfile.objects.all():
        row.ical_token = uuid.uuid4()
        row.save(update_fields=['ical_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_ical_token'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
