# Generated by Django 4.2.27 on 2026-01-27 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_populate_unique_tokens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="google_refresh_token",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ical_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique token for iCal feed subscription",
                unique=True,
            ),
        ),
    ]
