# Generated by Django 4.2.27 on 2026-01-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_ical_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="google_refresh_token",
        ),
    ]
