# Generated by Django 4.2.27 on 2026-01-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_google_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_refresh_token",
            field=models.CharField(
                blank=True,
                help_text="OAuth refresh token for Google Calendar",
                max_length=255,
            ),
        ),
    ]
