# Generated by Django 4.2.27 on 2026-01-26 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_booked", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "availability_slot",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes from the patient"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor_calendar_event_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "patient_calendar_event_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="scheduling.availabilityslot",
                    ),
                ),
            ],
            options={
                "db_table": "booking",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "created_at"],
                        name="booking_patient_a438c1_idx",
                    ),
                    models.Index(
                        fields=["doctor", "created_at"],
                        name="booking_doctor__57346f_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="availabilityslot",
            index=models.Index(
                fields=["doctor", "date", "is_booked"],
                name="availabilit_doctor__6953ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityslot",
            index=models.Index(
                fields=["date", "is_booked"], name="availabilit_date_4eda03_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availabilityslot",
            unique_together={("doctor", "date", "start_time")},
        ),
    ]
