# Generated by Django 4.2.27 on 2026-01-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="doctor_calendar_event_id",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="patient_calendar_event_id",
        ),
    ]
