# Generated by Django 4.2.27 on 2026-01-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_remove_booking_doctor_calendar_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="google_event_id",
            field=models.CharField(
                blank=True, help_text="Google Calendar Event ID", max_length=255
            ),
        ),
    ]
